In [1]:
import pandas as pd

In [2]:
data_path = r'E:\machine_learning_practice\practice\machine_learning_projects\data\student_results.csv'

In [3]:
df = pd.read_csv(data_path)
df

,Date,Student ID,Class,Section,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,01-07-2019,1001.0,10,A,2.0,9,3,5,50.0
1,02-07-2019,1002.0,10,NaN,NaN,8,2,0,80.0
2,03-07-2019,NaN,10,NaN,3.0,8,2,4,60.0
3,06-07-2019,NaN,11,NaN,0.0,10,1,5,NaN
4,07-07-2019,1005.0,11,A,4.0,7,2,0,NaN
5,08-07-2019,NaN,11,D,10.0,7,0,0,NaN
6,09-07-2019,1007.0,12,B,4.0,6,0,0,80.0
7,10-07-2019,1008.0,12,C,NaN,6,2,0,90.0
8,11-07-2019,1009.0,12,A,NaN,8,2,4,60.0
9,12-07-2019,1010.0,12,D,6.0,9,1,0,85.0

In [4]:
df.interpolate()

C:\Users\Jeet\AppData\Local\Temp\ipykernel_23148\4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

,Date,Student ID,Class,Section,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,01-07-2019,1001.0,10,A,2.000000,9,3,5,50.0
1,02-07-2019,1002.0,10,NaN,2.500000,8,2,0,80.0
2,03-07-2019,1003.0,10,NaN,3.000000,8,2,4,60.0
3,06-07-2019,1004.0,11,NaN,0.000000,10,1,5,65.0
4,07-07-2019,1005.0,11,A,4.000000,7,2,0,70.0
5,08-07-2019,1006.0,11,D,10.000000,7,0,0,75.0
6,09-07-2019,1007.0,12,B,4.000000,6,0,0,80.0
7,10-07-2019,1008.0,12,C,4.666667,6,2,0,90.0
8,11-07-2019,1009.0,12,A,5.333333,8,2,4,60.0
9,12-07-2019,1010.0,12,D,6.000000,9,1,0,85.0

In [5]:
df.interpolate(method= 'linear')

C:\Users\Jeet\AppData\Local\Temp\ipykernel_23148\1450789841.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method= 'linear')

,Date,Student ID,Class,Section,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,01-07-2019,1001.0,10,A,2.000000,9,3,5,50.0
1,02-07-2019,1002.0,10,NaN,2.500000,8,2,0,80.0
2,03-07-2019,1003.0,10,NaN,3.000000,8,2,4,60.0
3,06-07-2019,1004.0,11,NaN,0.000000,10,1,5,65.0
4,07-07-2019,1005.0,11,A,4.000000,7,2,0,70.0
5,08-07-2019,1006.0,11,D,10.000000,7,0,0,75.0
6,09-07-2019,1007.0,12,B,4.000000,6,0,0,80.0
7,10-07-2019,1008.0,12,C,4.666667,6,2,0,90.0
8,11-07-2019,1009.0,12,A,5.333333,8,2,4,60.0
9,12-07-2019,1010.0,12,D,6.000000,9,1,0,85.0

In [6]:
df.interpolate(method= 'time')

C:\Users\Jeet\AppData\Local\Temp\ipykernel_23148\771701644.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method= 'time')

ValueError: time-weighted interpolation only works on Series or DataFrames with a DatetimeIndex

In [7]:
type(df.Date[0])

str

In [8]:
df = pd.read_csv(data_path,parse_dates=['Date'])
df

,Date,Student ID,Class,Section,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,2019-01-07,1001.0,10,A,2.0,9,3,5,50.0
1,2019-02-07,1002.0,10,NaN,NaN,8,2,0,80.0
2,2019-03-07,NaN,10,NaN,3.0,8,2,4,60.0
3,2019-06-07,NaN,11,NaN,0.0,10,1,5,NaN
4,2019-07-07,1005.0,11,A,4.0,7,2,0,NaN
5,2019-08-07,NaN,11,D,10.0,7,0,0,NaN
6,2019-09-07,1007.0,12,B,4.0,6,0,0,80.0
7,2019-10-07,1008.0,12,C,NaN,6,2,0,90.0
8,2019-11-07,1009.0,12,A,NaN,8,2,4,60.0
9,2019-12-07,1010.0,12,D,6.0,9,1,0,85.0

In [ ]:
type(df.Date[0])

In [9]:
df = pd.read_csv(data_path,parse_dates=['Date'],index_col='Date')
df

,Student ID,Class,Section,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Date,,,,,,,,
2019-01-07,1001.0,10,A,2.0,9,3,5,50.0
2019-02-07,1002.0,10,NaN,NaN,8,2,0,80.0
2019-03-07,NaN,10,NaN,3.0,8,2,4,60.0
2019-06-07,NaN,11,NaN,0.0,10,1,5,NaN
2019-07-07,1005.0,11,A,4.0,7,2,0,NaN
2019-08-07,NaN,11,D,10.0,7,0,0,NaN
2019-09-07,1007.0,12,B,4.0,6,0,0,80.0
2019-10-07,1008.0,12,C,NaN,6,2,0,90.0
2019-11-07,1009.0,12,A,NaN,8,2,4,60.0
2019-12-07,1010.0,12,D,6.0,9,1,0,85.0

In [10]:
df.interpolate(method= 'time')

C:\Users\Jeet\AppData\Local\Temp\ipykernel_23148\771701644.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method= 'time')

,Student ID,Class,Section,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Date,,,,,,,,
2019-01-07,1001.00,10,A,2.000000,9,3,5,50.000000
2019-02-07,1002.00,10,NaN,2.525424,8,2,0,80.000000
2019-03-07,1002.56,10,NaN,3.000000,8,2,4,60.000000
2019-06-07,1004.40,11,NaN,0.000000,10,1,5,70.000000
2019-07-07,1005.00,11,A,4.000000,7,2,0,73.260870
2019-08-07,1006.00,11,D,10.000000,7,0,0,76.630435
2019-09-07,1007.00,12,B,4.000000,6,0,0,80.000000
2019-10-07,1008.00,12,C,4.659341,6,2,0,90.000000
2019-11-07,1009.00,12,A,5.340659,8,2,4,60.000000
2019-12-07,1010.00,12,D,6.000000,9,1,0,85.000000

In [11]:
df.interpolate(method= 'index')

C:\Users\Jeet\AppData\Local\Temp\ipykernel_23148\3116227336.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method= 'index')

,Student ID,Class,Section,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Date,,,,,,,,
2019-01-07,1001.00,10,A,2.000000,9,3,5,50.000000
2019-02-07,1002.00,10,NaN,2.525424,8,2,0,80.000000
2019-03-07,1002.56,10,NaN,3.000000,8,2,4,60.000000
2019-06-07,1004.40,11,NaN,0.000000,10,1,5,70.000000
2019-07-07,1005.00,11,A,4.000000,7,2,0,73.260870
2019-08-07,1006.00,11,D,10.000000,7,0,0,76.630435
2019-09-07,1007.00,12,B,4.000000,6,0,0,80.000000
2019-10-07,1008.00,12,C,4.659341,6,2,0,90.000000
2019-11-07,1009.00,12,A,5.340659,8,2,4,60.000000
2019-12-07,1010.00,12,D,6.000000,9,1,0,85.000000

In [12]:
df = pd.read_csv(data_path,parse_dates=['Date'],index_col='Class')
df

,Date,Student ID,Section,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
Class,,,,,,,,
10,2019-01-07,1001.0,A,2.0,9,3,5,50.0
10,2019-02-07,1002.0,NaN,NaN,8,2,0,80.0
10,2019-03-07,NaN,NaN,3.0,8,2,4,60.0
11,2019-06-07,NaN,NaN,0.0,10,1,5,NaN
11,2019-07-07,1005.0,A,4.0,7,2,0,NaN
11,2019-08-07,NaN,D,10.0,7,0,0,NaN
12,2019-09-07,1007.0,B,4.0,6,0,0,80.0
12,2019-10-07,1008.0,C,NaN,6,2,0,90.0
12,2019-11-07,1009.0,A,NaN,8,2,4,60.0
12,2019-12-07,1010.0,D,6.0,9,1,0,85.0

In [13]:
df.interpolate(method= 'index')

C:\Users\Jeet\AppData\Local\Temp\ipykernel_23148\3116227336.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method= 'index')

NotImplementedError:

In [14]:
df.interpolate(method= 'nearest')

C:\Users\Jeet\AppData\Local\Temp\ipykernel_23148\2224705008.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method= 'nearest')

NotImplementedError: