In [1]:
import pandas as pd

In [7]:
data_path = r'E:\machine_learning_practice\practice\machine_learning_projects\data\student_results3.csv'

In [8]:
df = pd.read_csv(data_path)
df

,Student ID,Class,Section,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,A,2,9,3,5,50
1,1002,10,B,6,8,2,0,80
2,1003,10,C,3,8,2,4,60
3,1004,11,D,0,10,1,5,45
4,1005,11,A,4,7,2,0,75
5,1006,11,B,10,7,0,0,96
6,1007,12,C,4,6,0,0,80
7,1008,12,D,10,6,2,0,90
8,1009,12,A,2,8,2,4,60
9,1010,12,B,6,9,1,0,85

In [9]:
gr1 = df.groupby(by='Section')

In [10]:
gr1

In [11]:
gr1.groups

{'A': [0, 4, 8], 'B': [1, 5, 9], 'C': [2, 6], 'D': [3, 7]}

In [12]:
df.groupby(['Section','Class']).groups

{('A', 10): [0], ('A', 11): [4], ('A', 12): [8], ('B', 10): [1], ('B', 11): [5], ('B', 12): [9], ('C', 10): [2], ('C', 12): [6], ('D', 11): [3], ('D', 12): [7]}

In [14]:
for Section,df_1 in gr1:
    print(Section)
    print(df_1)

A
   Student ID  Class Section  Study hrs  Sleeping hrs  Social Media usage hrs  \
0        1001     10       A          2             9                       3
4        1005     11       A          4             7                       2
8        1009     12       A          2             8                       2

   Mobile Games hrs  Percantege
0                 5          50
4                 0          75
8                 4          60
B
   Student ID  Class Section  Study hrs  Sleeping hrs  Social Media usage hrs  \
1        1002     10       B          6             8                       2
5        1006     11       B         10             7                       0
9        1010     12       B          6             9                       1

   Mobile Games hrs  Percantege
1                 0          80
5                 0          96
9                 0          85
C
   Student ID  Class Section  Study hrs  Sleeping hrs  Social Media usage hrs  \
2        1003     10       C          3             8                       2
6        1007     12       C          4             6                       0

   Mobile Games hrs  Percantege
2                 4          60
6                 0          80
D
   Student ID  Class Section  Study hrs  Sleeping hrs  Social Media usage hrs  \
3        1004     11       D          0            10                       1
7        1008     12       D         10             6                       2

   Mobile Games hrs  Percantege
3                 5          45
7                 0          90

In [15]:
list(gr1)

[('A',
     Student ID  Class Section  Study hrs  Sleeping hrs  Social Media usage hrs  \
  0        1001     10       A          2             9                       3
  4        1005     11       A          4             7                       2
  8        1009     12       A          2             8                       2

     Mobile Games hrs  Percantege
  0                 5          50
  4                 0          75
  8                 4          60  ),
 ('B',
     Student ID  Class Section  Study hrs  Sleeping hrs  Social Media usage hrs  \
  1        1002     10       B          6             8                       2
  5        1006     11       B         10             7                       0
  9        1010     12       B          6             9                       1

     Mobile Games hrs  Percantege
  1                 0          80
  5                 0          96
  9                 0          85  ),
 ('C',
     Student ID  Class Section  Study hrs  Sleeping hrs  Social Media usage hrs  \
  2        1003     10       C          3             8                       2
  6        1007     12       C          4             6                       0

     Mobile Games hrs  Percantege
  2                 4          60
  6                 0          80  ),
 ('D',
     Student ID  Class Section  Study hrs  Sleeping hrs  Social Media usage hrs  \
  3        1004     11       D          0            10                       1
  7        1008     12       D         10             6                       2

     Mobile Games hrs  Percantege
  3                 5          45
  7                 0          90  )]

In [16]:
dict(list(gr1))

{'A':    Student ID  Class Section  Study hrs  Sleeping hrs  Social Media usage hrs  \
 0        1001     10       A          2             9                       3
 4        1005     11       A          4             7                       2
 8        1009     12       A          2             8                       2

    Mobile Games hrs  Percantege
 0                 5          50
 4                 0          75
 8                 4          60  ,
 'B':    Student ID  Class Section  Study hrs  Sleeping hrs  Social Media usage hrs  \
 1        1002     10       B          6             8                       2
 5        1006     11       B         10             7                       0
 9        1010     12       B          6             9                       1

    Mobile Games hrs  Percantege
 1                 0          80
 5                 0          96
 9                 0          85  ,
 'C':    Student ID  Class Section  Study hrs  Sleeping hrs  Social Media usage hrs  \
 2        1003     10       C          3             8                       2
 6        1007     12       C          4             6                       0

    Mobile Games hrs  Percantege
 2                 4          60
 6                 0          80  ,
 'D':    Student ID  Class Section  Study hrs  Sleeping hrs  Social Media usage hrs  \
 3        1004     11       D          0            10                       1
 7        1008     12       D         10             6                       2

    Mobile Games hrs  Percantege
 3                 5          45
 7                 0          90  }

In [19]:
df.groupby('Class').get_group(12)

,Student ID,Class,Section,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
6,1007,12,C,4,6,0,0,80
7,1008,12,D,10,6,2,0,90
8,1009,12,A,2,8,2,4,60
9,1010,12,B,6,9,1,0,85

In [20]:
df.groupby('Section').get_group('A')

,Student ID,Class,Section,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,A,2,9,3,5,50
4,1005,11,A,4,7,2,0,75
8,1009,12,A,2,8,2,4,60