In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({'ID':[1,2,3,4],'Class':[9,10,11,12]})
df1

   ID  Class
0   1      9
1   2     10
2   3     11
3   4     12

In [4]:
df2 = pd.DataFrame({'ID':[1,2,3,4],'Name':['A','B','C','D']})
df2

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D

In [6]:
pd.merge(df1,df2, on = 'ID')

   ID  Class Name
0   1      9    A
1   2     10    B
2   3     11    C
3   4     12    D