In [1]:
import pandas as pd

In [2]:
sr1 = pd.Series([0,1,2])
sr1

0    0
1    1
2    2
dtype: int64

In [3]:
sr2 = pd.Series([3,4,5])
sr2

0    3
1    4
2    5
dtype: int64

In [4]:
pd.concat([sr1,sr2])

0    0
1    1
2    2
0    3
1    4
2    5
dtype: int64

In [6]:
df1 = pd.DataFrame({
    'ID':[1,2,3,4],
    'Name':['A','B','C','D'],
    'Class':[5,6,7,8]
})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [7]:
df2 = pd.DataFrame({
    'ID':[5,6,7,8],
    'Name':['E','F','G','H'],
    'Class':[9,10,11,12]
})
df2

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [10]:
pd.concat([df1,df2])

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [11]:
pd.concat([df1,df2],axis=1)

   ID Name  Class  ID Name  Class
0   1    A      5   5    E      9
1   2    B      6   6    F     10
2   3    C      7   7    G     11
3   4    D      8   8    H     12

In [13]:
pd.concat([df1,df2],axis=0,ignore_index = True)

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
4   5    E      9
5   6    F     10
6   7    G     11
7   8    H     12

In [14]:
df1 = pd.DataFrame({
    'ID':[1,2,3,4],
    'Name':['A','B','C','D'],
    'Class':[5,6,7,8]
})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [15]:
df2 = pd.DataFrame({
    'ID':[3,4],
    'Name':['C','D'],
    'Class':[7,8]
})
df2

   ID Name  Class
0   3    C      7
1   4    D      8

In [17]:
pd.concat([df1,df2])

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
0   3    C      7
1   4    D      8

In [18]:
pd.concat([df1,df2],axis= 1)

   ID Name  Class   ID Name  Class
0   1    A      5  3.0    C    7.0
1   2    B      6  4.0    D    8.0
2   3    C      7  NaN  NaN    NaN
3   4    D      8  NaN  NaN    NaN

In [19]:
pd.concat([df1,df2],axis= 1, join = 'inner')

   ID Name  Class  ID Name  Class
0   1    A      5   3    C      7
1   2    B      6   4    D      8