In [1]:
import pandas as pd

In [4]:
data_path = r'E:\machine_learning_practice\practice\machine_learning_projects\data\movie_ratings.csv'

In [8]:
df = pd.read_csv(data_path,sep='\t')
df

       Genre  Year  Budget(M$)  Ratings %
0     Action  2008          28         48
1     Action  2009         200         63
2     Action  2008          32         57
3     Action  2010          20         52
4  Adventure  2009          18         84
5  Adventure  2010         105         44
6     Comedy  2010          20         70
7     Comedy  2008           8         81
8     Comedy  2009          30         71

In [9]:
df.pivot_table(index = 'Genre')

           Budget(M$)  Ratings %     Year
Genre
Action      70.000000       55.0  2008.75
Adventure   61.500000       64.0  2009.50
Comedy      19.333333       74.0  2009.00

In [11]:
df.pivot_table(index = 'Genre',columns='Year')

          Budget(M$)               Ratings %
Year            2008   2009   2010      2008  2009  2010
Genre
Action          30.0  200.0   20.0      52.5  63.0  52.0
Adventure        NaN   18.0  105.0       NaN  84.0  44.0
Comedy           8.0   30.0   20.0      81.0  71.0  70.0

In [13]:
df.pivot_table(index = 'Genre',columns='Year',aggfunc='count')

          Budget(M$)           Ratings %
Year            2008 2009 2010      2008 2009 2010
Genre
Action           2.0  1.0  1.0       2.0  1.0  1.0
Adventure        NaN  1.0  1.0       NaN  1.0  1.0
Comedy           1.0  1.0  1.0       1.0  1.0  1.0

In [14]:
df.pivot_table(index = 'Genre',columns='Year',aggfunc='max')

          Budget(M$)               Ratings %
Year            2008   2009   2010      2008  2009  2010
Genre
Action          32.0  200.0   20.0      57.0  63.0  52.0
Adventure        NaN   18.0  105.0       NaN  84.0  44.0
Comedy           8.0   30.0   20.0      81.0  71.0  70.0

In [15]:
df.pivot_table(index = 'Genre',columns='Year',aggfunc='sum')

          Budget(M$)               Ratings %
Year            2008   2009   2010      2008  2009  2010
Genre
Action          60.0  200.0   20.0     105.0  63.0  52.0
Adventure        NaN   18.0  105.0       NaN  84.0  44.0
Comedy           8.0   30.0   20.0      81.0  71.0  70.0

In [16]:
df.pivot_table(index = 'Genre',columns='Year',fill_value='none')

C:\Users\Jeet\AppData\Local\Temp\ipykernel_21740\3958601296.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.pivot_table(index = 'Genre',columns='Year',fill_value='none')

          Budget(M$)               Ratings %
Year            2008   2009   2010      2008  2009  2010
Genre
Action          30.0  200.0   20.0      52.5  63.0  52.0
Adventure       none   18.0  105.0      none  84.0  44.0
Comedy           8.0   30.0   20.0      81.0  71.0  70.0

In [18]:
df.pivot_table(index = 'Genre',columns='Year',fill_value=0,margins=True)

          Budget(M$)                                    Ratings %             \
Year            2008        2009        2010        All      2008       2009
Genre
Action     30.000000  200.000000   20.000000  70.000000      52.5  63.000000
Adventure   0.000000   18.000000  105.000000  61.500000       0.0  84.000000
Comedy      8.000000   30.000000   20.000000  19.333333      81.0  71.000000
All        22.666667   82.666667   48.333333  51.222222      62.0  72.666667


Year            2010        All
Genre
Action     52.000000  55.000000
Adventure  44.000000  64.000000
Comedy     70.000000  74.000000
All        55.333333  63.333333