# DataFrame

In [1]:
import pandas as pd

In [2]:
emt_df = pd.DataFrame()
print(emt_df)

Empty DataFrame
Columns: []
Index: []

In [3]:
lst = ['a','b','c']
print(lst)

['a', 'b', 'c']

In [4]:
df1 = pd.DataFrame(lst)
print(df1)

   0
0  a
1  b
2  c

In [5]:
df1

   0
0  a
1  b
2  c

In [6]:
ls_of_ls = [[1,2,3],[2,3,4],[4,5,6]]
print(ls_of_ls)

[[1, 2, 3], [2, 3, 4], [4, 5, 6]]

In [7]:
df2 = pd.DataFrame(ls_of_ls)

In [8]:

df2

   0  1  2
0  1  2  3
1  2  3  4
2  4  5  6

In [9]:
dict1 = {'ID':[11,22,33,44]}
dict1

{'ID': [11, 22, 33, 44]}

In [10]:
df3 = pd.DataFrame(dict1)
df3

   ID
0  11
1  22
2  33
3  44

In [13]:
dict1 = {'ID':[11,22,33,44],'SN':[1,2,3,4]}
dict1

{'ID': [11, 22, 33, 44], 'SN': [1, 2, 3, 4]}

In [14]:
df3 = pd.DataFrame(dict1)
df3

   ID  SN
0  11   1
1  22   2
2  33   3
3  44   4

In [16]:
ls_dict = [{'a':1,'b':2},{'a':3,'b':4}]
df5 = pd.DataFrame(ls_dict)
df5

   a  b
0  1  2
1  3  4

In [17]:
ls_dict = [{'a':1,'b':2},{'a':3,'b':4,'c':5}]
df5 = pd.DataFrame(ls_dict)
df5

   a  b    c
0  1  2  NaN
1  3  4  5.0

In [18]:
dict_sr = {'Id':pd.Series([1,2,3]),'SN':[111,222,333]}
df6 = pd.DataFrame(dict_sr)
df6

   Id   SN
0   1  111
1   2  222
2   3  333