# Handling missing values

In [1]:
import pandas as pd

In [2]:
data_path = r'E:\machine_learning_practice\practice\machine_learning_projects\data\Fortune_10_pd4.csv'

In [3]:
df = pd.read_csv(data_path)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,NaN,2009,"$10,573,990","7,435,363 Dollars",3138627,NaN
5,6,Techline,NaN,2006,"$13,898,119","5,470,303 Dollars",8427816,not available
6,7,Cityace,NaN,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,NaN,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [6]:
df = pd.read_csv(data_path, na_values=["not available",'no values'])
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,NaN
4,5,Techdrill,NaN,2009,"$10,573,990","7,435,363 Dollars",3138627,NaN
5,6,Techline,NaN,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7,Cityace,NaN,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,NaN,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [8]:
df = pd.read_csv(data_path)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,no values,2009,"$10,573,990","7,435,363 Dollars",3138627,NaN
5,6,Techline,NaN,2006,"$13,898,119","5,470,303 Dollars",8427816,not available
6,7,Cityace,NaN,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,NaN,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [10]:
df = pd.read_csv(data_path, na_values={'Industry':'no values','Growth':'not available'})
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,NaN
4,5,Techdrill,NaN,2009,"$10,573,990","7,435,363 Dollars",3138627,NaN
5,6,Techline,NaN,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7,Cityace,NaN,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,NaN,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [11]:
df = pd.read_csv(data_path,keep_default_na=False)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,no values,2009,"$10,573,990","7,435,363 Dollars",3138627,null
5,6,Techline,#N/A,2006,"$13,898,119","5,470,303 Dollars",8427816,not available
6,7,Cityace,#N/A,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [12]:
df = pd.read_csv(data_path, na_filter = False)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,not available
4,5,Techdrill,no values,2009,"$10,573,990","7,435,363 Dollars",3138627,null
5,6,Techline,#N/A,2006,"$13,898,119","5,470,303 Dollars",8427816,not available
6,7,Cityace,#N/A,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%