# Handling missing values 2

In [1]:
import pandas as pd

In [2]:
data_path = r'E:\machine_learning_practice\practice\machine_learning_projects\data\Fortune_10_pd5.csv'

In [3]:
df = pd.read_csv(data_path)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,NaN
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,NaN
4,5,Techdrill,NaN,2009,"$10,573,990","7,435,363 Dollars",3138627,NaN
5,6,Techline,NaN,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7,Cityace,NaN,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,NaN,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [4]:
df.isnull()

      ID   Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  False  False     False      False    False     False   False   False
1  False  False     False      False    False     False   False   False
2  False  False     False      False    False     False   False    True
3  False  False     False      False    False     False   False    True
4  False  False      True      False    False     False   False    True
5  False  False      True      False    False     False   False    True
6  False  False      True      False    False     False   False   False
7  False  False      True      False    False     False   False   False
8  False  False     False      False    False      True   False   False
9  False  False     False      False    False     False   False   False

In [7]:
df.isnull().sum()

ID           0
Name         0
Industry     4
Inception    0
Revenue      0
Expenses     1
Profit       0
Growth       4
dtype: int64

In [9]:
df.isnull().sum().sum()

9

In [10]:
df = pd.read_csv(data_path)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,NaN
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,NaN
4,5,Techdrill,NaN,2009,"$10,573,990","7,435,363 Dollars",3138627,NaN
5,6,Techline,NaN,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7,Cityace,NaN,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,NaN,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [11]:
df.notnull()

     ID  Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0  True  True      True       True     True      True    True    True
1  True  True      True       True     True      True    True    True
2  True  True      True       True     True      True    True   False
3  True  True      True       True     True      True    True   False
4  True  True     False       True     True      True    True   False
5  True  True     False       True     True      True    True   False
6  True  True     False       True     True      True    True    True
7  True  True     False       True     True      True    True    True
8  True  True      True       True     True     False    True    True
9  True  True      True       True     True      True    True    True

In [12]:
df.notnull().sum()

ID           10
Name         10
Industry      6
Inception    10
Revenue      10
Expenses      9
Profit       10
Growth        6
dtype: int64

In [13]:
df.notnull().sum().sum()

71

# Series

In [14]:
import numpy as np
sr = pd.Series([1,2,3,np.nan,4,np.NAN])
sr

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [15]:
sr.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [16]:
sr.isnull().sum()

2

In [17]:
sr.isnull().sum()

2