# Handling missing value 3

In [1]:
import pandas as pd

In [2]:
data_path = r'E:\machine_learning_practice\practice\machine_learning_projects\data\Fortune_10_pd6.csv'

In [3]:
df = pd.read_csv(data_path)
df

    ID             Name            Industry      Profit Growth
0  1.0          Lamtone         IT Services   5274553.0    30%
1  2.0        Stripfind  Financial Services  11412916.0    20%
2  3.0  Canecorporation              Health   3005820.0     7%
3  4.0              NaN         IT Services   6597557.0    NaN
4  5.0             Mark                 NaN   5674893.0    21%
5  NaN              NaN                 NaN         NaN    NaN
6  NaN              NaN                 NaN         NaN    NaN
7  NaN              NaN                 NaN         NaN    NaN
8  NaN              NaN                 NaN         NaN    NaN
9  NaN              NaN                 NaN         NaN    NaN

In [4]:
df.dropna()

    ID             Name            Industry      Profit Growth
0  1.0          Lamtone         IT Services   5274553.0    30%
1  2.0        Stripfind  Financial Services  11412916.0    20%
2  3.0  Canecorporation              Health   3005820.0     7%