# Handling missing value

In [1]:
import pandas as pd

In [2]:
data_path = r'E:\machine_learning_practice\practice\machine_learning_projects\data\Fortune_10_pd7.csv'

In [3]:
df = pd.read_csv(data_path)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",NaN,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,NaN,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,NaN,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,NaN
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [4]:
df.fillna(0)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,0,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,0,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,0
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",0,11901180.0,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [5]:
df.fillna(2)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",2.0,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,2,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,2,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,2
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",2,11901180.0,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [6]:
df.fillna({'Name':'none','profit':0,'Growth':0})

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",NaN,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,none,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,none,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,0
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [7]:
df.fillna(method='ffill')

C:\Users\Jeet\AppData\Local\Temp\ipykernel_19644\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",3005820.0,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Techdrill,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,Techdrill,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,23%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180.0,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [9]:
df.fillna(method='bfill')

C:\Users\Jeet\AppData\Local\Temp\ipykernel_19644\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",3138627.0,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Kayelectronics,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,Kayelectronics,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,4%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180","5,635,276 Dollars",11901180.0,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [11]:
df.fillna(method = 'ffill', axis = 0)

C:\Users\Jeet\AppData\Local\Temp\ipykernel_19644\3382854290.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill', axis = 0)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",3005820.0,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Techdrill,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,Techdrill,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,23%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180.0,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [12]:
df.fillna(method = 'ffill', axis = 1)

C:\Users\Jeet\AppData\Local\Temp\ipykernel_19644\3272608729.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill', axis = 1)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars","7,429,377 Dollars",26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,6,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,7,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,3005116.0
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180","$14,001,180",11901180.0,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%